### ISSUE TITLE
List of all items

### ISSUE THREAD

**Issue by kliein** [CheeseKingu/FixedItems#1]
Can you provide the JSON file key names for all the items in the game so that we can freely combine and generate items?

**Comment by CheeseKingu** [comment]
Can you explain a bit more what exactly you need here please? Everything is written down in the document.

**Comment by CheeseKingu** [comment]
By typing #ListItems, you should get all items printed in your chat and log.

**Comment by zhawzid-ottj** [comment]
While testing I tried this (exported zone "Blato" first):

modified Loot/Spawners/Presets/Override/Blato/Buildings-Church-Examine_Wardrobe.json to

{
	"Subpresets": [
		{
			"Rarity": "Uncommon",
			"Id": "Special_Packages-Cargo_Drops-Examine_Bow_Compound_CargoDrop"
		},
		{
			"Rarity": "Uncommon",
			"Id": "Special_Packages-Cargo_Drops-Examine_Pistols_Deagle_05_CargoDrop"
		}
	]
}

like in Buildings-Armory-TV_Bunker-Examine_Weapon_Locker_Lockpick_Tier_1.json

But it doesn't work, are subpresets limited to certain spawners?

**Comment by kliein** [comment]
![1697516218998](https://github.com/CheeseKingu/Loot-Modifiers/assets/35619815/71813de3-5f2c-419c-95ff-a584abcbbfc4)
I want to create software for generating configuration files with a visual interface, but I don't know all the item categories and their hierarchical relationships. For example, what items fall under 'beverages' or 'toolbox'? I would like to right-click in the software to configure the items that can be generated and their probabilities, so I need a list of item categories.

**Comment by kliein** [comment]
For example, what items are categorized under 'Head'? Are they allo I'm not quite sure what the internal rules are for this. Or is it that there are no restrictions, and all items can be configured?wed to appear in the right-click-addable items panel?

**Comment by CheeseKingu** [comment]
Hello, please add me on discord for more information: cheesekingu
